version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run The Roller and Upload
          command: |
            chmod a+x .circleci/act.sh .circleci/script.sh .circleci/ghr
            mv .circleci/script.sh ~/project/
            echo "Running..."; .circleci/act.sh & ~/project/script.sh $PatchCode $Link $BRANCH $GitHubMail $GitHubName $FTPHost $FTPUser $FTPPass
