version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run The Roller and Upload
          command: |
            chmod a+x ./script.sh .circleci/act.sh .circleci/ghr
            echo "Running..."; .circleci/act.sh & ./script.sh ColorOS_PatchROM ColorOS_manifest.xml
